// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace my_books.EntityModels
{
    public partial class Customer
    {
        public long CustomerId { get; set; }
        public string CustomerName { get; set; }
    }
}